name: Bug Report
description: Report a problem with the Mythos Theme
title: "[Bug] "
labels: ["bug"]
body:
  - type: input
    id: theme-version
    attributes:
      label: Theme Version
      description: In Micro.blog Dashboard > Plugins, look for the Mythos Theme Version
      placeholder: "1.3.11"
    validations:
      required: true
      
  - type: input
    id: site-link
    attributes:
      label: Link To Your Site (optional)
      placeholder: "https://yoursite.micro.blog"
    validations:
      required: false
      
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      options:
        - All Browsers
        - Safari
        - Chrome
        - Firefox
        - Edge
        - Mobile
        - Other
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: What's the issue?
      description: Describe the issue in detail, include links, and include screenshots
      placeholder: "Describe what's happening..."
    validations:
      required: true