name: Bug Report
description: Report a problem with the Mythos Theme
title: "[Bug] "
labels: ["bug"]
body:
  - type: input
    id: theme-version
    attributes:
      label: Theme Version
      description: In Dashboard > Design, look for the Mythos Theme version
      placeholder: "1.3.10"
    validations:
      required: true
      
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      options:
        - Safari
        - Chrome
        - Firefox
        - Edge
        - Mobile
        - Other
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: What's the problem?
      placeholder: "Describe what's broken..."
    validations:
      required: true
      
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots (optional)
      description: Drag and drop images here
    validations:
      required: false