name: Bug Report
description: Report a problem with the Mythos Theme
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug! Please fill out the information below to help us reproduce and fix the issue.
        
  - type: input
    id: theme-version
    attributes:
      label: Theme Version
      description: In your Micro.blog Dashboard, click **Plug-ins** to see the Mythos Theme version
      placeholder: "v1.3.10"
    validations:
      required: true
      
  - type: input
    id: hugo-version
    attributes:
      label: Hugo Version
      description: In your Micro.blog Dashboard, scroll down to see the Hugo version
      placeholder: "v0.128.0"
    validations:
      required: false
      
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you seeing this issue in?
      options:
        - Safari
        - Chrome
        - Firefox
        - Edge
        - Mobile Safari (iOS)
        - Mobile Chrome (Android)
        - Other (please specify in description)
    validations:
      required: true
      
  - type: dropdown
    id: device
    attributes:
      label: Device Type
      description: What type of device are you using?
      options:
        - Desktop/Laptop
        - Mobile Phone
        - Tablet
        - Other
    validations:
      required: true
      
  - type: textarea
    id: other-plugins
    attributes:
      label: Other Plugins
      description: List any other plugins you have installed (found in Micro.blog Dashboard > Plug-ins)
      placeholder: |
        - Plugin Name 1 v1.0.0
        - Plugin Name 2 v2.1.0
        - etc.
    validations:
      required: false
      
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug in detail. What were you doing when it occurred?
      placeholder: "When I click on..."
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: Describe what you expected to see instead
      placeholder: "I expected..."
    validations:
      required: true
      
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error
    validations:
      required: true
      
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: |
        Please attach screenshots if applicable. You can drag and drop images here.
        **Tip:** Screenshots of both the issue AND your browser's developer console (F12) are very helpful!
      placeholder: "Drag and drop screenshots here or click to upload"
    validations:
      required: false
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other details that might be relevant (custom CSS, specific post types, etc.)
    validations:
      required: false
      
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have checked that this issue hasn't already been reported
          required: true
        - label: I have provided enough information to reproduce the issue
          required: true