name: Feature Request
description: Suggest a new feature for the Mythos Theme
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: request
    attributes:
      label: What would you like to see added and why would it be useful?
      placeholder: "I'd like the theme to... This would be useful because..."
    validations:
      required: true