name: Feature Request
description: Suggest a new feature or improvement for the Mythos Theme
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please provide as much detail as possible to help us understand your request.
        
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the problem or limitation you're experiencing
      placeholder: "I find it frustrating when..."
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Describe your ideal solution
      description: What would you like to see added or changed?
      placeholder: "I would like..."
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative solutions
      description: Have you considered any alternative approaches or workarounds?
      placeholder: "I've tried..."
    validations:
      required: false
      
  - type: dropdown
    id: priority
    attributes:
      label: How important is this to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my workflow
        - Critical/blocking my use
    validations:
      required: true
      
  - type: textarea
    id: examples
    attributes:
      label: Examples or mockups
      description: |
        Share examples, mockups, or references from other themes/sites. 
        You can drag and drop images here.
    validations:
      required: false
      
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched for similar feature requests
          required: true
        - label: This feature would benefit other Mythos Theme users (not just me)
          required: true