name: Question
description: Ask a question about the Mythos Theme
title: "[Question] "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: What's your question?
      description: Please include any links to help with answering the question
      placeholder: "How do I..."
    validations:
      required: true